### ISSUE TITLE
Explain colors

### ISSUE THREAD

**Issue by wiz21b** [regexident/cargo-modules#104]
As a new rust user I'm very confused about modules. I found your tool and wanted to use it to better understand how rust understands my module structure. It's really helpful. Now it uses color and I didn't find a documentation explaining what red, green, yellow mean. Same goes for things in parenthesis, what do they mean ? parent module ? something else ?

As said in your doc, the cargo-module is here to help people manage complexity in big projects. So I repeat, it's also useful for new users with very small tutorial-like projects to understand the working of the rust modules.

**Comment by regexident** [comment]
Hi @wiz21b, thanks for getting in touch!

You are absolutely right in that the colors should be documented somewhere, but aren't.

PR https://github.com/regexident/cargo-modules/pull/105 aims to fix this. 🙂

I'm glad you have so far found the tool helpful while learning Rust!
