### ISSUE TITLE
fails to install on windows

### ISSUE THREAD

**Issue by kaem-e** [regexident/cargo-modules#198]
tried installing via cargo `cargo install cargo-modules` & it seems to get stuck at something to do with `ServerCapabilities`
![image](https://github.com/regexident/cargo-modules/assets/46230985/bed88d1b-eda4-4136-ab36-d6e3551b79c5)

> For reference, I'm on windows 11, PowerShell 7 and ran cargo update beforehand, (1.72.1)

**Comment by alearcy** [comment]
Same!

**Comment by regexident** [comment]
Thanks for the report! Could you check if the issue still exists for the just released 0.9.3 release?

**Comment by kaem-e** [comment]
yup that seemed to work!, ill close the issue thank you!
