### ISSUE TITLE
Analyze crates in non-test mode

### ISSUE THREAD

**Issue by asomers** [regexident/cargo-modules#20]
"cargo modules --graph" analyzes the crate in test mode.  This frequently includes extra modules that aren't interesting for understanding the design of a crate, like modules that only contain tests.  Sometimes, a crate's module dependencies can differ more radically in test mode, such as when the test_double crate is in use.  It would be better to analyze the module graph in non-test mode.

**Comment by hmvp** [comment]
Cargo modules only shows test modules if you enable conditional modules. If you don't use that option it won't show them. It still analyses them though. 

I assume that this suits your needs. However it might be an idea to distinguish between test only and other conditional modules... In case someone has a lot of those...

**Comment by asomers** [comment]
Close, but not quite.  Cargo modules still doesn't show a module if it's imported like this:
```rust
#[cfg(not(test))]
use something;
```

**Comment by asomers** [comment]
In the latest build (of the edition-2018-graph-with-dependencies branch) conditional modules seem to be enabled by default, with no way to disable them.

I would suggest that the best behavior would be to display the modules in non-test mode, allowing the user to set any crate features on the command line.

**Comment by muhuk** [comment]
This seems to be something I have overlooked.  Could you drop a note on the patch, I'll try to fix it.

**Comment by regexident** [comment]
This should now be fixed with https://github.com/regexident/cargo-modules/pull/66 having been merged. 🎉 😃
<sub>(The release still needs a it more work. If you're feeling lucky you can install from source and give it a try, though.)</sub>
