### ISSUE TITLE
NetBSD package merged

### ISSUE THREAD

**Issue by 0323pin** [regexident/cargo-modules#206]
FYI, I've just packaged `cargo-modules` and merged it  into pkgsrc main branch. Commit log for you reference [here](https://mail-index.netbsd.org/pkgsrc-changes/2023/10/12/msg283626.html)

The package will soon be available to users. To install it, there are two options. Either, a pre-compiled binary using `pkgin install cargo-modules` or, building locally from source using:
```
cd /usr/pkgsrc/devel/cargo-modules
make install
```

Regards

**Comment by 0323pin** [comment]
Inform, done, close.

**Comment by regexident** [comment]
Thank you @0323pin!
