### ISSUE TITLE
cargo-modules structure --types --traits --fns --tests ==> error: unexpected argument '--types' found

### ISSUE THREAD

**Issue by rtdietrich** [regexident/cargo-modules#248]
If I try your example
```
cargo-modules structure --types --traits --fns --tests
```
I got this:
error: unexpected argument '--types' found

**Comment by regexident** [comment]
Hi @rtdietrich, it looks like the README examples got out of sync with the recent CLI changes. I've opened a fix PR.

The CLI filters of `cargo-modules` used to be opt-in, which resulted in common commands becoming rather verbose.
So with the new CLI commands such filters were flipped from opt-in (`--types --traits --fns`) to opt-out (`--no-types --no-traits --no-fns`).

The `--tests`, `--cfg-test` and `--no-cfg-test` options were merged into just `--cfg-test`: setting it simulates a `cargo test --no-run` build.

The tree-generating command used to look like this:

```terminal
cargo-modules generate tree --types --traits --fns --tests
```

And now looks like this:

```terminal
cargo-modules structure --cfg-test
```

with the `--cfg-test` being optional.

See `cargo-modules structure --help` for all the options recognized by the command.
