### ISSUE TITLE
--plain option doesn't seem to work as expected

### ISSUE THREAD

**Issue by qrilka** [regexident/cargo-modules#26]
`cargo-modules` uses `gold` for some edges and it's almost invisible when printed on BW laser printer.
So I've tried to use `--plain` option but with no luck:
```
$ cargo modules --plain graph | grep color | head -1
	"::storage-units" [label="storage-units",color=green];
$ cargo modules graph | grep color | head -1
	"::storage-units" [label="storage-units",color=green];
```
i.e. the end result stays the same

**Comment by regexident** [comment]
Hi @qrilka good catch!

Originally `cargo modules` only supported printing of tree-like command-line diagrams, which would show up like this in the console …

```plain
quote : crate
 ├── __rt : public
 ├── to_tokens : private
 └── tokens : private
     └── private : private
```

… but like this then piped to another process …

```

[1;34m[0m[1;32mquote[0m : [1;36mcrate[0m
[1;34m ├── [0m[1;32m__rt[0m : [1;36mpublic[0m
[1;34m ├── [0m[1;33mto_tokens[0m : [1;36mprivate[0m
[1;34m └── [0m[1;33mtokens[0m : [1;36mprivate[0m
[1;34m     └── [0m[1;33mprivate[0m : [1;36mprivate[0m
```

`--plain` was meant to reduce the noise for the latter scenario.

When we added `graph`-mode we simply forgot to make it be respected by that mode, too. 😇

Fortunately though adding a simple check on `self.config.colored` to [dot_printer.rs#L38-L45](https://github.com/regexident/cargo-modules/blob/271f377549a0921988feef3237ffb5cd8302ceb7/src/dot_printer.rs#L38-L45) should fix it.
