### ISSUE TITLE
Can cargo-modules still generate a dot-file with the module structure?

### ISSUE THREAD

**Issue by barafael** [regexident/cargo-modules#266]
`cargo modules generate graph > mods.dot` used to generate a nice DOT format file. Is this still possible?

**Comment by regexident** [comment]
The new CLI's equivalent would be this:

```terminal
cargo modules dependencies [OPTIONS] > mods.dot
```

while the opt-in flags have been replaced with corresponding opt-out flags:

```
--no-externs    Filter out extern items from extern crates from graph
--no-fns        Filter out functions (e.g. fns, async fns, const fns) from graph
--no-modules    Filter out modules (e.g. `mod foo`, `mod foo {}`) from graph
--no-sysroot    Filter out sysroot crates (`std`, `core` & friends) from graph
--no-traits     Filter out traits (e.g. trait, unsafe trait) from graph
--no-types      Filter out types (e.g. structs, unions, enums) from graph
--no-uses       Filter out "use" edges from graph
```

So if you're only interested in modules, the you'd have to opt out of everything else:

```
cargo modules dependencies --no-externs --no-fns --no-sysroot --no-traits --no-types --no-uses > mods.dot
```

**Comment by barafael** [comment]
Oof. Thanks for patiently clarifying!

**Comment by regexident** [comment]
Unfortunately there is no one-size-fits-all when it comes to those flag defaults and I found myself pretty much always using just about all the opt-ins, which from what I can tell also seems to match most other people's usages.

Having them as opt-out also results in —I think— improved CLI accessibility as you're much more likely to miss out of an opt-in feature than you are on one that's opt-out, which was the second major reason for the change.

There is also a little bit more information in the corresponding [CHANGELOG entry](https://github.com/regexident/cargo-modules/blob/main/CHANGELOG.md#0130---2023-12-14).
