### ISSUE TITLE
Differentiate between modules with the same name

### ISSUE THREAD

**Issue by qrilka** [regexident/cargo-modules#28]
It's valid in Rust to have equally named modules to appear in different places of module hierarchy. `cargo-modules` shows them as 2 entries with the same name and just looking at that picture there is no way to understand where which modules is shown. One option to resolve this is to allow full module paths to be used or just to show with a parent module if there are any name clashes.

**Comment by regexident** [comment]
Hi @qrilka, thanks for reporting!

I suppose you're referring to `cargo modules graph`?
In `cargo modules tree` the paths are implicitly fully qualified by the tree's branch structure.

**Comment by qrilka** [comment]
Oh, sorry for missing that detail, right, I was looking into dot file for a project I'm reviewing and noticed this detail.

**Comment by regexident** [comment]
We should have all the data we need to fix this. I'm not too familiar with `cargo modules graph` though, as @hmvp is the one who contributed the command to **cargo-modules**. What do you think @hmvp?

**Comment by regexident** [comment]
This should now be fixed with https://github.com/regexident/cargo-modules/pull/66 having been merged. 🎉 😃
<sub>(The release still needs a it more work. If you're feeling lucky you can install from source and give it a try, though.)</sub>
