### ISSUE TITLE
Doesn't understand the `crate` keyword

### ISSUE THREAD

**Issue by asomers** [regexident/cargo-modules#29]
As of Rust 1.30.0, the `crate` keyword indicates that a path should begin from the crate root.  It's a lot like a leading `::` on a path.  But cargo-modules's graph command doesn't understand it, and simply omits imports that use the new keyword.

For example, cargo-modules understands an import like `use ::foo::bar;`, but not `use crate::foo::bar`.

https://blog.rust-lang.org/2018/10/25/Rust-1.30.0.html

**Comment by asomers** [comment]
Still an issue with rustc 1.32.0-nightly (4a45578bc 2018-12-07).

**Comment by regexident** [comment]
Hi @asomers!

Thanks for reporting. Unfortunately the 2018 edition of Rust made the whole path resolving topic quite a bit more complicated than it already was before.

I'm aware of the issue though and looking into things. I just can't guarantee any near-term fix just yet.

**Comment by muhuk** [comment]
I would like to take a crack at this. Appreciate if you can share any pointers @regexident. I know I need to get into `tree` & `dot_printer` for starters.

**Comment by muhuk** [comment]
I gave it a try [here](https://github.com/muhuk/cargo-modules/tree/understand-crate-keyword).

It didn't work out quite well.

I think I will try again but this time take a different approach; I will try detecting the edition and if it's `"2018"` give control to an alternate implementation.

@regexident would that be okay if I changed `cargo-modules` to be `"2018"` edition?

**Comment by regexident** [comment]
> @regexident would that be okay if I changed cargo-modules to be "2018" edition?

Would be fine with me. 👍🏻

**Comment by regexident** [comment]
This should now be fixed with https://github.com/regexident/cargo-modules/pull/66 having been merged. 🎉 😃
<sub>(The release still needs a it more work. If you're feeling lucky you can install from source and give it a try, though.)</sub>
