### ISSUE TITLE
Broken lines in modules with more than one feature

### ISSUE THREAD

**Issue by andrey-gvrd** [regexident/cargo-modules#3]
Repo on which it breaks: https://github.com/hackndev/zinc

![cargo-modules-bug](https://cloud.githubusercontent.com/assets/5842980/16493389/e6d8c1c6-3eaa-11e6-98a2-f2ba8a030056.png)

**Comment by regexident** [comment]
Oh, good catch. Hadn't come across any multi-line attributes in my testing.
A simple `s/\n/ /` should probably be enough to fix it though.

Thanks for reporting! With a bit of luck I might find time to fix it later today.
