### ISSUE TITLE
Cannot compile rustc-ap-syntax on latest nightly

### ISSUE THREAD

**Issue by latex** [regexident/cargo-modules#44]
error[E0046]: not all trait items implemented, missing: `mixed_site`
   --> /home/leandro/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-ap-syntax-583.0.0/ext/proc_macro_server.rs:657:1
    |
657 | impl server::Span for Rustc<'_> {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing `mixed_site` in implementation
    |
    = note: `mixed_site` from trait: `fn(&mut Self) -> <Self as proc_macro::bridge::server::Types>::Span`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0046`.
error: could not compile `rustc-ap-syntax`.
warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by regexident** [comment]
Resolved by #47
