### ISSUE TITLE
Feature request: Option to list all public types

### ISSUE THREAD

**Issue by rw** [regexident/cargo-modules#48]
It would be great to be able to list all public types, instead of just modules. Is this feasible and desired?

Thank you!

**Comment by regexident** [comment]
Hi @rw, that sounds like a reasonable addition!

And the logic required for it shouldn't be too different from the one we already use for discovery of modules, I guess.

**Comment by rw** [comment]
Thank you!

Hmm, maybe public/private, depending on a flag?

**Comment by regexident** [comment]
See https://github.com/regexident/cargo-modules/issues/64 (closed as duplicate) for a nice draft of how such a feature might look like.

**Comment by regexident** [comment]
This should now be fixed with https://github.com/regexident/cargo-modules/pull/66 having been merged. 🎉 😃
<sub>(The release still needs a it more work. If you're feeling lucky you can install from source and give it a try, though.)</sub>
