### ISSUE TITLE
Module graph missing links

### ISSUE THREAD

**Issue by kvark** [regexident/cargo-modules#51]
Hi all! This is one great project, and I'm looking forward to use to for good.
Just trying it on [WebRender](https://github.com/servo/webrender), I'm missing quite a few links in the generated module graph:

![mod-graph](https://user-images.githubusercontent.com/107301/81098604-9957c380-8ed7-11ea-9ce4-8361bc2c1fa9.png)

This was generated via the following command, using the code from #50 :
```rust
cargo-modules --enable-edition-2018 graph | dot -Tpng > mod-graph.png
```
I removed the top-level `Cargo.toml` to convince it that it's not a cargo workspace (otherwise it doesn't work at all, see https://github.com/regexident/cargo-modules/issues/8#issuecomment-624159548).
It shows the graph to be pretty flat, even though the modules clearly depend on each other a lot. For example, no arrows originate from `batch` module, even though it clearly uses [a whole bunch of stuff](https://github.com/servo/webrender/blob/66166116600929175f73d6e8b59b4f023deae17d/webrender/src/batch.rs#L8-L33).

Is this a known issue? Is it related to 2018 edition (cc @muhuk)? Anything I could help with to investigate?

**Comment by kvark** [comment]
I suspect #34 is just not finished yet. I tried copying the "example-lib-edition-2018" out (of the workspace) and generating the graph from it:
```
../cargo-modules/target/debug/cargo-modules --enable-edition-2018 graph | dot -Tpng >example.png
```
It produced the following picture:
![example](https://user-images.githubusercontent.com/107301/81132602-08a3d680-8f1d-11ea-9645-5b13538534a0.png)

It looks to be missing all the back edges ("submodule" -> "A", "subsubbmodule" -> "submodule", "A").

**Comment by kvark** [comment]
One issue that I realized here is that cargo-modules doesn't even realize that `subsubmodule` is a module. On the graph, it shows it as an orphan. I [asked about this](https://rust-lang.zulipchat.com/#narrow/stream/182449-t-compiler.2Fhelp/topic/Using.20rustc_ap_rustc_parse.3A.3Aparse_crate_from_file) on Rust Zulip, and the answer was:
> simulacrum: iirc mod statements are "inlined" during expansion
> simulacrum: so you won't actually parse the submodule (or the subsubmodule) until expansion runs

I don't yet understand the whole picture. Maybe @regexident you can shed some light on it?
Also, it would be nice to reach you on some more immediate medium, like the Matrix/Zulip/Gitter/etc

**Comment by regexident** [comment]
Before Rust 2018 the complexity of name/module resolution reasonably simple.
Rust 2018 made things considerably more complex.

@muhuk has been spearheading most of the efforts to add full support for Rust 2018, with me mostly doing code review and joining in on discussions on implementation details.

---

In light of the recent ["library-ification"](http://smallcultfollowing.com/babysteps/blog/2020/04/09/libraryification/) by the Rust compiler team I more and more wonder if it wouldn't make sense to tap into some of the logic/crates that are falling out of these efforts, the great work @matklad is doing with [rust-analyzer](https://github.com/rust-analyzer/rust-analyzer) in particular, such as [ra_hir](https://github.com/rust-analyzer/rust-analyzer/tree/guide-2019-01/crates/ra_hir), which might be able to solve the whole name resolution issue for us for free.

**Comment by regexident** [comment]
This should now be fixed with https://github.com/regexident/cargo-modules/pull/66 having been merged. 🎉 😃
<sub>(The release still needs a it more work. If you're feeling lucky you can install from source and give it a try, though.)</sub>
