### ISSUE TITLE
Using rust-analyzer

### ISSUE THREAD

**Issue by pksunkara** [regexident/cargo-modules#63]
From https://github.com/rust-analyzer/rust-analyzer/pull/4405, you guys can use RA to run this.

I have a visitor trait code (I can extract this to a separate crate) you guys can use.

But from what I understand, you guys do not need it and can do something like [this](https://github.com/pksunkara/cargo-up/blob/891515d6bf23c8383f7631a16beb08ae9e5233db/cargo-up/src/lib/preloader.rs#L26-L270)

**Comment by regexident** [comment]
Hi @pksunkara,

first of all, thanks for coming around! 👋🏻 

> From [rust-analyzer/rust-analyzer#4405](https://github.com/rust-analyzer/rust-analyzer/pull/4405), you guys can use RA to run this.

That's exactly what I'm looking into right now (and reason for me commenting on the aforementioned issue). 😃

> I have a visitor trait code (I can extract this to a separate crate) you guys can use.

That would be great, actually! Something like `ra_ap_visitor`?

> But from what I understand, you guys do not need it and can do something like [this](https://github.com/pksunkara/cargo-up/blob/891515d6bf23c8383f7631a16beb08ae9e5233db/cargo-up/src/lib/preloader.rs#L26-L270)

There are quite a few feature requests that would benefit from a full-featured visit, so having access to your `trait Visitor` would be huge!

**Comment by pksunkara** [comment]
Here is the visitor [code](https://github.com/pksunkara/cargo-up/blob/master/cargo-up/src/lib/visitor.rs) (notice the macros to enable us to develop it faster). I haven't made it public but it's trivial to do so.

You can see it's usage [here](https://github.com/pksunkara/cargo-up/blob/891515d6bf23c8383f7631a16beb08ae9e5233db/cargo-up/src/lib/runner.rs#L169). And the call is [here](https://github.com/pksunkara/cargo-up/blob/891515d6bf23c8383f7631a16beb08ae9e5233db/cargo-up/src/lib/runner.rs#L114).

Look at it and if you are sure that you want to use this, I will extract it out immediately and publish. And then we can both keep adding to it as we need.

**Comment by regexident** [comment]
@pksunkara I took the liberty to create a [PR](https://github.com/pksunkara/cargo-up/pull/2) with an improved Visitor, adding missing node types as we would definitely need a few more for cargo-modules.

Also, yes please create a crate with it! 🙏🏻

**Comment by pksunkara** [comment]
Thanks! I was actually just about to do start working on what you did. 😄 

I will create a crate and publish it.

**Comment by pksunkara** [comment]
@regexident Shall we close this? I assume you have everything you need to start and you have other issues that actually track the features.

**Comment by regexident** [comment]
Well, since the initial goal is to get feature parity with a new core using RA I think this issue is fine to remain open.

I'm working on a prototype right now, in fact. 🙂

I however ended up requiring (and writing) a HIR visitor, not an AST visitor (as your crate provides), as we need canonicalized paths and other semantic info.

**Comment by pksunkara** [comment]
Hopefully you release that as a separate crate. I currently use a small subset of it too, but more manually written instead of visitor.

**Comment by regexident** [comment]
I definitely will!

Or maybe we should rename `rust_visitor::Visitor` to `rust_visitor::ast::Visitor` and add it to `rust_visitor` as `rust_visitor::hir::Visitor`?
This would make discovery easier. You wouldn't have to guess that there's a separate 3rd party crate with a hir visitor.
And `rust_visitor` is a sufficiently generic name to provide both.

**Comment by pksunkara** [comment]
Sounds good to me. I added you to the repo. Feel free to commit to that crate directly

**Comment by regexident** [comment]
👍

**Comment by regexident** [comment]
@pksunkara I ended up not using it. This was it before I remove the file:

<details>

<summary>hir_visitor.rs</summary>

```rust
use ra_ap_hir::{
    self as hir, db::HirDatabase, Adt, BuiltinType, Const, Function, Module, ModuleDef, Static,
    Trait, TypeAlias, Variant,
};

use ra_ap_ide_db::RootDatabase;

pub use ra_ap_syntax;

pub type Semantics<'db> = ra_ap_hir::Semantics<'db, RootDatabase>;

macro_rules! visiting {
    () => {};
    ($($kind:ident => $method:ident as $type:ident,)*) => {
        trait Visitable: Sized {
            fn accept<T: Visitor>(&self, visitor: &mut T, db: &dyn HirDatabase);
        }

        impl Visitable for ModuleDef {
            fn accept<T: Visitor>(&self, visitor: &mut T, db: &dyn HirDatabase) {
                visitor.pre_visit(self);

                match self {
                    $(ModuleDef::$kind(def) => def.accept(visitor, db),)*
                };

                visitor.post_visit(self);
            }
        }

        pub trait Visitor: Sized {
            /// Call this method to perform a in-order traversal on `node` and its children.
            fn walk(&mut self, module_def: &ModuleDef, db: &dyn HirDatabase) {
                module_def.accept(self, db);
            }

            /// This method is called before visiting a node.
            fn pre_visit(&mut self, _module_def: &ModuleDef) {}

            /// This method is called after visiting a node.
            fn post_visit(&mut self, _module_def: &ModuleDef) {}

            /// This method is called when visiting a node of the given type.
            $(fn $method(&mut self, _def: &hir::$type) {})*
        }
    };
}

visiting!(
    Module => visit_module as Module,
    Function => visit_function as Function,
    Adt => visit_adt as Adt,
    Variant => visit_variant as Variant,
    Const => visit_const as Const,
    Static => visit_static as Static,
    Trait => visit_trait as Trait,
    TypeAlias => visit_type_alias as TypeAlias,
    BuiltinType => visit_builtin_type as BuiltinType,
);

impl Visitable for Module {
    fn accept<T: Visitor>(&self, visitor: &mut T, db: &dyn HirDatabase) {
        visitor.visit_module(self);

        for child in self.clone().declarations(db) {
            child.accept(visitor, db);
        }
    }
}

impl Visitable for Function {
    fn accept<T: Visitor>(&self, visitor: &mut T, _db: &dyn HirDatabase) {
        visitor.visit_function(self);
    }
}

impl Visitable for Adt {
    fn accept<T: Visitor>(&self, visitor: &mut T, _db: &dyn HirDatabase) {
        visitor.visit_adt(self);
    }
}

impl Visitable for Variant {
    fn accept<T: Visitor>(&self, visitor: &mut T, _db: &dyn HirDatabase) {
        visitor.visit_variant(self);
    }
}

impl Visitable for Const {
    fn accept<T: Visitor>(&self, visitor: &mut T, _db: &dyn HirDatabase) {
        visitor.visit_const(self);
    }
}

impl Visitable for Static {
    fn accept<T: Visitor>(&self, visitor: &mut T, _db: &dyn HirDatabase) {
        visitor.visit_static(self);
    }
}

impl Visitable for Trait {
    fn accept<T: Visitor>(&self, visitor: &mut T, _db: &dyn HirDatabase) {
        visitor.visit_trait(self);
    }
}

impl Visitable for TypeAlias {
    fn accept<T: Visitor>(&self, visitor: &mut T, _db: &dyn HirDatabase) {
        visitor.visit_type_alias(self);
    }
}

impl Visitable for BuiltinType {
    fn accept<T: Visitor>(&self, visitor: &mut T, _db: &dyn HirDatabase) {
        visitor.visit_builtin_type(self);
    }
}
```

</details>

Feel free to add it to your rust-visitor crate. :+1:

**Comment by regexident** [comment]
I needed more fine-grained control over how to walk the graph, i.e. drive the walk, rather than be driven by it.
