### ISSUE TITLE
Modules in subdirectories are not shown

### ISSUE THREAD

**Issue by 1tgr** [regexident/cargo-modules#65]
This code produces output as expected:

```rust
pub mod mod1 {
    mod mod2 {
        pub fn mod2_fn() {}
    }

    mod mod3 {
        use crate::mod1::mod2;

        pub fn mod3_fn() {
            mod2::mod2_fn()
        }
    }

    pub use mod3::mod3_fn;
}

pub fn crate_fn() {
    mod1::mod3_fn()
}
```

```
# cargo modules tree

temp : crate
 └── mod1 : public
     ├── mod2 : private
     └── mod3 : private
```

However when I move the same code into a standard directory structure there is almost no output from `cargo modules`:

```
# find . -name "*.rs"
./src/lib.rs
./src/mod1/mod.rs
./src/mod1/mod3.rs
./src/mod1/mod2.rs
```

```
# cargo modules tree

temp : crate
 └── mod1 : public
```

`cargo modules graph` is affected in the same way.

I installed `cargo modules` using nightly toolchain 2020-10-19.

**Comment by regexident** [comment]
Hi @1tgr, could you share the content of each of your dummy files, so I can try to reproduce the issue?

**Comment by 1tgr** [comment]
```rust
// src/lib.rs
pub mod mod1;

pub fn crate_fn() {
    mod1::mod3_fn()
}

// src/mod1/mod.rs
mod mod2;
mod mod3;

pub use mod3::mod3_fn;

// src/mod1/mod2.rs
use crate::mod1::mod2;

pub fn mod3_fn() {
    mod2::mod2_fn()
}

// src/mod1/mod2.rs
pub fn mod2_fn() {
    println!("hello world")
}
```

It's the same code but split into separate files in a directory structure. Thanks!

**Comment by 1tgr** [comment]
And the Cargo.toml - it's 2018 edition:

```rust
[package]
name = "temp"
version = "0.1.0"
authors = ["Tim Robinson"]
edition = "2018"
```

**Comment by regexident** [comment]
Thanks @1tgr!

**Comment by 1tgr** [comment]
I'm guessing there's been some recent change in the nightly compiler's AST that causes cargo-modules to no longer visit the inner modules. If you have a previous nightly where it works I can use that instead.

**Comment by regexident** [comment]
Yes, certainly! This of course did work. It's the tool's whole job after all. 😅

**Comment by 1tgr** [comment]
In the AST, lib.rs has two items: `mod mod1` and `fn crate_fn`. I can see that `mod mod1` appears as `ItemKind::Mod(Mod { inline: false, items: [] })`. That is, it's recognised as a non-inline module; the rustc parser hasn't recursed inside it, which causes an empty `items` vec, which causes it to be silently skipped over by `cargo-modules`.

I don't see any attempt by the rustc parser to open mod1.rs and parse it. I'm not familiar with the compiler internals, but it looks like source files are opened and read by a single function, which is hit by my debugger breakpoint only for lib.rs. Likewise, at the system call level, I only see file access for lib.rs, nothing on mod1.rs.

I wonder if the program is expected to examine the AST and explicitly parse non-inline modules?

**Comment by 1tgr** [comment]
I don't see anything at the AST level that can expand the `items` of an `inline: false` module. Glancing at the rustdoc source code (which is in a similar situation to cargo-modules) I can see it works with HIR not AST.

**Comment by asomers** [comment]
Note that the problem happens even with cargo-modules's own example files.  In the test-resources/example-lib-edition-2018 directory, cargo modules wrongly reports subsubmodule as an orphan.
```
$ cargo modules -o tree

example-lib-edition-2018 : crate
 ├── A : private
 ├── submodule : public
 │   └── subsubmodule : orphan
 └── tests : private @ #[cfg(test)]
```

**Comment by reedrosenbluth** [comment]
Has anyone managed to get this working?

**Comment by regexident** [comment]
I'm currently finishing a major rewrite (based on rust-analyzer's internal crates, rather than rustc's) that addresses the issue among several others: #66

I just need to get around to update the README and add a CHANGES file, then I'll publish an update to crates.io.

If you feel lucky you can you checkout the PR and install from source.
`cargo modules --help` should give you some hints on what's changed.
As should reading the comments in #66.

**Comment by reedrosenbluth** [comment]
Cool thanks! Will give it a go

**Comment by regexident** [comment]
This should now be fixed with https://github.com/regexident/cargo-modules/pull/66 having been merged. 🎉 😃
<sub>(The release still needs a it more work. If you're feeling lucky you can install from source and give it a try, though.)</sub>
