### ISSUE TITLE
How to show dependencies between modules?

### ISSUE THREAD

**Issue by kangalioo** [regexident/cargo-modules#73]
As a test, I created the following project structure:
```rust
// src/lib.rs
mod a;
mod b;
mod c;
mod d;
```
```rust
// src/a.rs
use crate::*;
struct A(C);
```
```rust
// src/b.rs
use crate::*;
struct B(C);
```
```rust
// src/c.rs
use crate::*;
struct C;
```
```rust
// src/d.rs
use crate::*;
struct D(A, C);
```
[test.zip](https://github.com/regexident/cargo-modules/files/6017571/test-cargo.zip)

And ran cargo-modules on it (`0.5.0-beta.2`) :
```sh
cargo modules generate graph | dot -Tpng > modules.png
```

It runs successfully and yields:
![modules](https://user-images.githubusercontent.com/21220820/108622753-1fc79c80-743b-11eb-9583-4798c2b4cda4.png)

As you can see, it does show the parent-child module relations quite well. I was wondering if it's possible to also show inter-module dependencies, to the spirit of the following?
![image](https://user-images.githubusercontent.com/21220820/108622783-556c8580-743b-11eb-9ef8-c52a1c8c1777.png)

**Comment by regexident** [comment]
Check out the [options](https://github.com/regexident/cargo-modules#print-crate-as-a-graph) provided by `generate graph`:

```terminal
--with-externs           Include used modules and types from extern crates
--with-orphans           Include orphaned modules (i.e. unused files in /src)
--with-tests             Include tests (e.g. `#[cfg(test)] mod tests { … }`)
--with-types             Include types (e.g. structs, enums)
--with-uses              Include used modules and types
```

The options are opt-in (i.e. additive), so without any opt-in all you get is the sub-module graph (i.e. `owns` edges only). To get dependencies (i.e. `uses` edges) you need to add the `--with-uses` option (for now, the options might still change in the future, hence the beta release):

```bash
cargo modules generate graph --with-uses | dot -Tpng > modules.png
```

**Comment by kangalioo** [comment]
Oh I'm sorry, I should have rtfm. Thank you
