### ISSUE TITLE
Ignore `build.rs` even if not listed in Cargo.toml

### ISSUE THREAD

**Issue by regexident** [regexident/cargo-modules#9]
As of lately cargo detects `build.rs` build-scripts even if they are not listed:

> ```
> [package]
> # ...
> build = "build.rs"
> ```
> 
> "The Rust file designated by the build command (relative to the package root) will be compiled and invoked before anything else is compiled in the package, allowing your Rust code to depend on the built or generated artifacts. **Note that if you do not specify a value for build but your package root does contains a "build.rs" file, Cargo will compile and invoke this file for you.**" – http://doc.crates.io/build-script.html

As such `cargo modules` should do so, too.

**Comment by hmvp** [comment]
Should be fixed with #38 
Since we rely on cargo metadata to specify targets and build.rs is a seperate target
