### ISSUE TITLE
Disable panic backtrace if an error occured

### ISSUE THREAD

**Issue by Arjentix** [regexident/cargo-modules#99]
I just thought it was a bug when I've ran this extension and got a big panic backtrace. It took me a while when I actually noticed a readable error message and suggestion with fix at the top.
May be it will be better to remove useless panic backtrace printing?

**Comment by regexident** [comment]
The `cargo-modules` tool shouldn't have any backtraces enabled, afaik. 🤔 
Do you by any chance have `RUST_BACKTRACE=1` defined in your terminal environment?

**Comment by Arjentix** [comment]
Well, yes, I have it enabled to develop my own project...
May be you can use a trick from this code: https://github.com/ajeetdsouza/zoxide/blob/main/src/main.rs ?

**Comment by regexident** [comment]
I'd rather not modify the environment like that as that would prevent a user from intentionally enabling backtraces for the purpose of crash debugging (e.g. me or other contributors, while working on `cargo-modules`).
